# Generated by Django 2.2.12 on 2022-04-23 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_name', models.CharField(max_length=100)),
                ('story_description', models.TextField(blank=True, null=True)),
                ('story_created_date', models.DateField(auto_now_add=True)),
                ('story_image', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoryInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_status', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=50)),
                ('story_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LikeandDislike.Story')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
