# Generated by Django 2.2.12 on 2022-04-25 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LikeandDislike', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storyinformation',
            old_name='user_details',
            new_name='user_id',
        ),
    ]
